### PR TITLE
Loadout Rework

### PR DESCRIPTION
**Pull request by BorderKeeper**
Reworked the folder structure, added my loadouts + AI loadouts, removed incompatible loadouts and changed naming scheme. Let me know what you think of this if it is suitable we can do this with all loadouts other mission makers have.
When all loadouts are in place we can start merging and verifying existing loadouts, there is no need for 10 Mk16 US loadouts, altough rather more than none IMO.

### CODE REVIEW

**Comment by Freddo3000** [comment]
Avoid merging from master to master, create a new branch whenever you want to create a pull request.

For the AI loadouts, please trim the fat on them. Makes it a lot easier to copy over if you don't have to scroll through the briefing. I'd cut it down to only
```
uniforms[] = {};
vests[] = {};
headgear[] = {};
goggles[] = {};
backpacks[] = {};
faces[] = {};
voices[] = {};
rifles[] = {};
launchers[] = {};
attachments[] = {};
```
the rest can simply be edited by the mission maker in question.

Titling and sorting loadouts can be better. With a previous loadout repository I've worked with we sorted them into a few categories:
* Western Factions
* Eastern Faction
* USA
* Russia
* Armaverse Factions
* Others

As for titles, I'd simply cut it down to `factionname_camo/weaponname_year`, IE `usarmy_m81_1985`, `IONPMC_winter_xm8`. Whoever made the loadout can either be in a comment at the top of each loadout, or in a separate credits file.

Furthermore on loadouts, ideally they should probably include all of the default before being submitted.

Anyhow, it is good that you're is stepping up and beginning work on this stuff. It'll be really useful once there starts to be a sizeable amount of loadouts available, and a proper framework for them in place.

Edit: The example loadout has a pretty decent info template that can be used: https://github.com/ARCOMM/Loadouts/blob/master/Example/README.md

**Comment by BorderKeeper** [comment]
Agreed with trimming the fat I included the fat for AI due to the enemyForces section in briefing which can be turned into README.md
Will trim it along with creating those.

When it comes to the naming scheme I would leave it as is for the initial upload and then rename it during processing as knowing the mission name will give you access to archub pictures which can be added to readme.md and the name can be used to gauge the quality, for example I have a lot of generic loadouts based on use and McPedro will probably have a lot of loadouts that are correctly themed.

I do not agree with filling the loadout with defaults as it is too much work. I would rather allow as many loadouts even incomplete ones as possible and then attempt to merge them all into one kicking out incomplete ones in favour of more complete ones.

Actions I propose: 
- Merge this with a ticket to process, trim and improve these loadouts. (This includes pulling picture from archub showing the loadout, renaming, trimming all from the .hpp no related to loadout)
- Decide on an appropriate naming scheme going forward (I would want to keep all meta-info about the origin of the loadouts, but I don't care much) (create a ticket for this)
- Decide if we should go with categories or not

All of this is work for the future and should be done in parallel to the upload process, hence why we should go with this inital merge and deal with problems with tickets. The upload process should be as simple as possible for the mission makers otherwise they will not do them. Getting them on github with minimal effort, should be priority #1

**Comment by Freddo3000** [comment]
Sounds a bit backwards as what you're saying is basically push to master, resolve issues later.

**Comment by BorderKeeper** [comment]
We need to redistribute the work and I am not optimistic enough to say that mission makers will use git. I want a rough base for them to copy that can then be turned either by them or by us into something workable. I will gladly fix this merge req. but the basic structure should be there now.

**Comment by BorderKeeper** [comment]
Will be carried out on a bigger scale under a different branch

**Pull request closed without merging**
